### ISSUE TITLE
It's not really be getter and setter.

### ISSUE THREAD

**Issue by doanthai** [WilsonGodoi/generate-getters-setters#1]
In your code, generated code is only pure function used to set and get value of field in class. But getter and setter in class for javascript in ES6 or later version (reference http://es6-features.org/#GetterSetter) must be bellow:
`set id(value: number): void {
       return this._id = number; 
}
get id(): number {
       return this._id: 
}`
You can see it have "set" and "get" before function name. Can you update that for ES6 or later version.

**Comment by WilsonGodoi** [comment]
Okay, I'll develop for the es6 too.

**Comment by WilsonGodoi** [comment]
The es6 feature is done. Thank you.
